<a href="https://colab.research.google.com/github/scottspurlock/Google_Colab_Start/blob/master/scratch_lab02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Working with files
When you start up a new Colab instance, you get a certain amount of space for files. Any files needed by your code should be added to this special directory. (Click the folder icon in the left menu to see what's there. Just a folder called sample_data to start.) These files are not saved between sessions, so they need to be downloaded each time you connect to Colab. The easiest way to do this is to use wget, which is a shell command that downloads files from a URL. The -O switch can be used to specify an name for the file.

## Files shared from Google Drive
If you are downloading a file shared in Google Drive, you may have a link like this:
https://drive.google.com/file/d/1LyfxvbvXNS6Tdd6q4ABlGJ7pLEqhCQBO

However, this link will get an html file, even if the underlying file is actually data, like csv.

You can get the actual file by pasting the file ID into this URL: https://drive.google.com/uc?export=download&id=XXXX

For example: https://drive.google.com/uc?export=download&id=1LyfxvbvXNS6Tdd6q4ABlGJ7pLEqhCQBO

The cell below shows an example of downloading a csv file and saving it as lab02_populations.csv



In [1]:
# Download the input file
!wget -O lab02_populations.csv "https://drive.google.com/uc?export=download&id=1LyfxvbvXNS6Tdd6q4ABlGJ7pLEqhCQBO"


--2021-01-03 19:45:27--  https://drive.google.com/uc?export=download&id=1LyfxvbvXNS6Tdd6q4ABlGJ7pLEqhCQBO
Resolving drive.google.com (drive.google.com)... 74.125.31.100, 74.125.31.101, 74.125.31.113, ...
Connecting to drive.google.com (drive.google.com)|74.125.31.100|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://doc-0o-9s-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/fes1v834m94o6p9m595rut0oc3d02qqs/1609703100000/10030589818980776592/*/1LyfxvbvXNS6Tdd6q4ABlGJ7pLEqhCQBO?e=download [following]
--2021-01-03 19:45:27--  https://doc-0o-9s-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/fes1v834m94o6p9m595rut0oc3d02qqs/1609703100000/10030589818980776592/*/1LyfxvbvXNS6Tdd6q4ABlGJ7pLEqhCQBO?e=download
Resolving doc-0o-9s-docs.googleusercontent.com (doc-0o-9s-docs.googleusercontent.com)... 172.217.204.132, 2607:f8b0:400c:c15::84
Connecting to doc-0o-9s-docs.googleusercontent.com (doc-0o-9s

In [2]:
import numpy as np
%precision %.2f

# Load the file into a numpy array, skipping the first (header) row.
poptable = np.loadtxt('lab02_populations.csv', skiprows=1, delimiter=',', dtype=int)

# remove duplicate rows and row with bad data
poptable = np.delete(poptable, (11, 12, 23), axis=0)
print(poptable)

# This shows the year, number of hares, number of lynxes, and number of carrots

[[ 1900 30000  4000 48300]
 [ 1901 47200  6100 48200]
 [ 1902 70200  9800 41500]
 [ 1903 77400 35200 38200]
 [ 1904 36300 59400 40600]
 [ 1905 20600 41700 39800]
 [ 1906 18100 19000 38600]
 [ 1907 21400 13000 42300]
 [ 1908 22000  8300 44500]
 [ 1909 25400  9100 42100]
 [ 1910 27100  7400 46000]
 [ 1911 40300  8000 46800]
 [ 1912 57000 12300 43800]
 [ 1913 76600 19500 40900]
 [ 1914 52300 45700 39400]
 [ 1915 19500 51100 39000]
 [ 1916 11200 29700 36700]
 [ 1917  7600 15800 41800]
 [ 1918 14600  9700 43300]
 [ 1919 16200 10100 41300]
 [ 1920 24700  8600 47300]]


## Option 2: Map Google Drive
You can click the Mount Drive button on the left or mount the drive programmatically.

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [4]:
import pandas as pd
pd.read_csv('/content/drive/MyDrive/Teaching/CSC 401 Data Mining and Machine Learning/2020 Spring/labs/lab02_populations.csv')


year   hare   lynx  carrot
0   1900  30000   4000   48300
1   1901  47200   6100   48200
2   1902  70200   9800   41500
3   1903  77400  35200   38200
4   1904  36300  59400   40600
5   1905  20600  41700   39800
6   1906  18100  19000   38600
7   1907  21400  13000   42300
8   1908  22000   8300   44500
9   1909  25400   9100   42100
10  1910  27100   7400   46000
11  1910  27100   7400   46000
12  1910  27100   7400   46000
13  1911  40300   8000   46800
14  1912  57000  12300   43800
15  1913  76600  19500   40900
16  1914  52300  45700   39400
17  1915  19500  51100   39000
18  1916  11200  29700   36700
19  1917   7600  15800   41800
20  1918  14600   9700   43300
21  1919  16200  10100   41300
22  1920  24700   8600   47300
23  1921     -1     -1   45200